# Source: local-external-secrets/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-12T10:35:39Z"
  deletionTimestamp: null
  name: 'local-external-secrets-0.0.6'
  annotations:
    meta.helm.sh/release-name: 'local-external-secrets'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: use v1
      sha: 53345343fd586a77d0bc9fec57ae12e5c96c830d
  gitCloneUrl: https://github.com/jenkins-x-charts/local-external-secrets.git
  gitHttpUrl: https://github.com/jenkins-x-charts/local-external-secrets
  gitOwner: jenkins-x-charts
  gitRepository: local-external-secrets
  name: 'local-external-secrets'
  releaseNotesURL: https://github.com/jenkins-x-charts/local-external-secrets/releases/tag/v0.0.6
  version: v0.0.6
status: {}
